version: '3.10'
services:
  postgres-db:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    env_file: ./config/.env
  server-django:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db
    links:
      - postgres-db
    command: /bin/bash -c "
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
