# Generated by Django 4.1.7 on 2023-02-16 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('routine_result_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('result', models.CharField(choices=[('NOT', 'NOT'), ('TRY', 'TRY'), ('DONE', 'DONE')], max_length=4)),
                ('routine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine.routine')),
            ],
            options={
                'db_table': 'routine_result',
            },
        ),
    ]
