# Generated by Django 4.1.7 on 2023-02-20 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routine', '0003_routineday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='routineday',
            name='routine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_day_set', to='routine.routine'),
        ),
        migrations.AddConstraint(
            model_name='routineday',
            constraint=models.UniqueConstraint(fields=('day', 'routine_id'), name='routine-day unique key'),
        ),
    ]
