# Generated by Django 4.1.7 on 2023-02-21 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0004_alter_routine_account_id_alter_routineday_routine_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routine',
            old_name='account_id',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='routineday',
            old_name='routine_id',
            new_name='routine',
        ),
        migrations.RemoveField(
            model_name='routineresult',
            name='routine_id',
        ),
        migrations.AddField(
            model_name='routineresult',
            name='routine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='routine_result_set', to='routine.routine'),
            preserve_default=False,
        ),
    ]
