# Generated by Django 4.1.7 on 2023-02-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0005_rename_account_id_routine_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routineday',
            name='day',
            field=models.CharField(choices=[('MON', 'MON'), ('TUE', 'TUE'), ('WED', 'WED'), ('THU', 'THU'), ('FRI', 'FRI'), ('SAT', 'SAT'), ('SUN', 'SUN')], max_length=3),
        ),
    ]
